//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistentesEvento
    {
        public bool Asistencia { get; set; }
        public bool Pago { get; set; }
        public double Cantidad { get; set; }
        public int IdAsistente { get; set; }
        public int IdEvento { get; set; }
    
        public virtual Asistentes Asistentes { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
