//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistentesEvento
    {

        public AsistentesEvento(int idAssistant, int IdEvent)
        {
            this.IdAsistente = idAssistant;
            this.IdEvento = IdEvent;
        }

        public bool Asistencia { get; set; }
        public bool Pago { get; set; }
        public double Cantidad { get; set; }
        public int IdAsistente { get; set; }
        public int IdEvento { get; set; }
    
        public virtual Asistentes Asistentes { get; set; }
        public virtual Eventos Eventos { get; set; }

        public override string ToString()
        {
            return Asistentes.Nombre + " " + Asistentes.Apellido;
        }
    }
}
