//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosFinancieros
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public double Monto { get; set; }
        public string Concepto { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public int IdActividad { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Presupuestos Presupuestos { get; set; }
    }
}
