//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosFinancieros
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public double Monto { get; set; }
        public string Concepto { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public int IdActividad { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Presupuestos Presupuestos { get; set; }
    }
}
