//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int Id { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Lugar { get; set; }
        public int IdActividad { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public override string ToString()
        {
            return
                Actividades.Tipo + ": " + Actividades.Titulo + "\nCosto: $" + Actividades.Costo + "    Cupo disponible: " + Actividades.Cupo +
                "\nFecha de inicio: " + FechaInicio + " " + "\nFecha fin: " + FechaFin;
        }
    }
}
