//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public bool Asignado { get; set; }
        public string Cargo { get; set; }
        public int IdEvento { get; set; }
        public int IdCuenta { get; set; }
        public Nullable<int> IdComite { get; set; }
    
        public virtual Comites Comites { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
