//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public bool Asignado { get; set; }
        public string Cargo { get; set; }
        public int IdEvento { get; set; }
        public int IdCuenta { get; set; }
        public Nullable<int> IdComite { get; set; }
    
        public virtual Comites Comites { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
